name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
    inputs:
      archive:
        description: 'Archive built package'
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'sbt'

    - name: Build
      run: sbt test

    - name: Package
      run: sbt Universal/packageBin

    - name: Archive
      uses: actions/upload-artifact@v3
      if: ${{ inputs.archive }}
      with:
        name: archived-build
        path: ./target/universal/*.zip
