name: Build on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - run: git config --global core.autocrlf false

    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'sbt'

    - name: Test
      run: sbt test

    - name: package
      run: sbt universal:packageBin

