name: Build on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - run: git config --global core.autocrlf false

    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'sbt'

    - name: apex-ls-checkout
      uses: actions/checkout@v2
      with:
        repository: apex-dev-tools/apex-ls
        path: './apex-ls'

    - name: apex-ls-compile
      working-directory: './apex-ls'
      run: sbt publishLocal

    - name: Test
      run: sbt test
