name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'sbt'

    - name: apex-ls-checkout
      uses: actions/checkout@v2
      with:
        repository: apex-dev-tools/apex-ls
        path: './apex-ls'
        token: ${{ secrets.KJ_AT }}

    - name: apex-ls-compile
      working-directory: './apex-ls'
      run: sbt publishLocal

    - name: Build
      run: sbt test
